In [37]:
import pandas as pd

In [38]:
data = {
    'name': ["ronaldo", "messi", "neymar"],
    "age": [40, 38, 34],
    "country": ["protugal", "argentina", "brazil"]
}
df = pd.DataFrame(data)
df

      name  age    country
0  ronaldo   40   protugal
1    messi   38  argentina
2   neymar   34     brazil

In [39]:
data = [
    ["ronaldo", 40, "Portugal"],
    ["messi", 38, "Argentina"],
    ["neymar", 34, "Brazil"],
]

df = pd.DataFrame(data, columns=["name", "age", "country"])
df

      name  age    country
0  ronaldo   40   Portugal
1    messi   38  Argentina
2   neymar   34     Brazil

In [40]:
# Accessing column
cols = df[["name", "country"]]
print(cols)


# Accessing row
print("ROW ACCESSING")
print(df.loc[1])
# df.iloc[] => means index of the row, where loc refers just row number

      name    country
0  ronaldo   Portugal
1    messi  Argentina
2   neymar     Brazil
ROW ACCESSING
name           messi
age               38
country    Argentina
Name: 1, dtype: object

In [ ]:
# creating column
df["city" ] = ["Feni", "Noakhali", "Lokkhipur"]


# removing a column
filtered = df.drop("age", axis=1) # its actually filtering
print(filtered)
# df.drop("country", axis=1, inplace=True) # now country will completely removed from the dataframe (NOTE: it cant be run twice, because, delete can be possible only once)

      name    country       city
0  ronaldo   Portugal       Feni
1    messi  Argentina   Noakhali
2   neymar     Brazil  Lokkhipur