In [3]:
import pandas as pd
import numpy as np

# Find missing value

In [4]:
x = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(x)

In [5]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [8]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [9]:
df.isna().sum() # number of null value in cols

A    1
B    0
C    2
D    3
dtype: int64

In [10]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Drop Missing row

In [11]:
df.dropna() # if find 1 null in the row, then drop it

     A  B    C    D
0  1.0  1  1.0  1.0

In [17]:
df.dropna(thresh=3) # at least 3 value, or drop

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Fill Missing Value

In [18]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [20]:
vals = {'A': 100, 'B': 200, 'C': 300, 'D': 400}
df.fillna(value=vals)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0

In [22]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0