In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("aircraft_flight_data.csv")
df

     time  altitude  airspeed   rpm
0       0    1000.8      58.1  2074
1       5    1009.6      58.0  2046
2      10    1021.7      57.9  2037
3      15    1029.5      58.1  2063
4      20    1041.4      58.3  2073
..    ...       ...       ...   ...
145   725    1976.7      85.4  2427
146   730    1979.4      85.5  2433
147   735    1977.3      85.0  2423
148   740    1982.6      85.4  2415
149   745    1986.6      85.5  2432

[150 rows x 4 columns]

In [4]:
df.head(5)

   time  altitude  airspeed   rpm
0     0    1000.8      58.1  2074
1     5    1009.6      58.0  2046
2    10    1021.7      57.9  2037
3    15    1029.5      58.1  2063
4    20    1041.4      58.3  2073

In [5]:
df.describe()

            time     altitude    airspeed          rpm
count  150.00000   150.000000  150.000000   150.000000
mean   372.50000  1776.882667   76.848000  2406.346667
std    217.22684   370.636071    8.164868   134.099081
min      0.00000  1000.800000   57.900000  2037.000000
25%    186.25000  1478.850000   72.800000  2395.500000
50%    372.50000  1947.100000   79.050000  2448.500000
75%    558.75000  2075.575000   82.400000  2502.000000
max    745.00000  2181.500000   87.100000  2556.000000

# Filtering

In [ ]:
# selecting data by feature
# df["airspeed"]
df[df["airspeed"] < 60]

KeyError: 0

# Sorting

In [7]:
df.sort_values("rpm", ascending=True)

     time  altitude  airspeed   rpm
2      10    1021.7      57.9  2037
1       5    1009.6      58.0  2046
3      15    1029.5      58.1  2063
4      20    1041.4      58.3  2073
0       0    1000.8      58.1  2074
..    ...       ...       ...   ...
79    395    2049.5      79.9  2542
97    485    2178.9      81.1  2547
96    480    2179.3      81.7  2547
112   560    2154.4      82.4  2555
92    460    2176.9      80.9  2556

[150 rows x 4 columns]